{
 "title": "System Resource Dashboard",
 "tags": [
  "metrics",
  "cadvisor"
 ],
 "templating": {
  "list": [
   {
    "name": "container",
    "label": "Select Container",
    "query": "label_values(container_memory_usage_bytes{container_label_com_docker_compose_service!=\"\"}, container_label_com_docker_compose_service)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 10, "h": 10 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=~\"$container\", id!=\"/\", name!=\"\"}[5m])",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "x": 10, "y": 0, "w": 10, "h": 10 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service=~\"$container\", id!=\"/\", name!=\"\"}",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 10, "w": 10, "h": 10 },
   "targets": [
    {
     "expr": "rate(container_blkio_device_usage_total{container_label_com_docker_compose_service=~\"$container\", operation=\"Read\", id!=\"/\", name!=\"\"}[5m])",
     "legendFormat": "{{container_label_com_docker_compose_service}}-read"
    },
    {
     "expr": "rate(container_blkio_device_usage_total{container_label_com_docker_compose_service=~\"$container\", operation=\"Write\", id!=\"/\", name!=\"\"}[5m])",
     "legendFormat": "{{container_label_com_docker_compose_service}}-write"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "x": 10, "y": 10, "w": 10, "h": 10 },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{container_label_com_docker_compose_service=~\"$container\", interface=\"eth0\", id!=\"/\", name!=\"\"}[5m])",
     "legendFormat": "TX Bytes ({{container_label_com_docker_compose_service}})"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{container_label_com_docker_compose_service=~\"$container\", interface=\"eth0\",id!=\"/\", name!=\"\"}[5m])",
     "legendFormat": "RX Bytes ({{container_label_com_docker_compose_service}})"
    }
   ]
  }
 ]
}